### ISSUE TITLE
 save --folders returns '_length_must_be_20_characters_long'

### ISSUE THREAD

**Issue by epcim** [zbentley/classeur-api-client#2]
Hi, I have tested recent update/fix on classeur-download (0.1.4) and got this new issue, the same I get

```
 body: 
   { status: 400,
     error: 'bad_request',
     reason: '"value"_length_must_be_20_characters_long' },
  headers: 
```

I guess API expects an ID string instead of folder name or so..

```
➜  classeur git:(master) ✗ /home/user/hg2g/workspace/node_modules/.bin/cldownload --user-id 'lJD3lp******O4h' --api-key 'aH32lF********i9uZ' save --folders 'OpenStack' --save-path /home/user/hg2g/workspace –markdown


# path, args
https://app.classeur.io/api/v1/folders/OpenStack {}

# console.log(error, body, response)
# error
{ Error: Received HTTP code 400 for GET https://app.classeur.io/api/v1/folders/OpenStack
    at Request._callback (/home/user/hg2g/workspace/node_modules/flashheart/lib/client.js:150:13)
    at Request.self.callback (/home/user/hg2g/workspace/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/user/hg2g/workspace/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/user/hg2g/workspace/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
  statusCode: 400,

# body
  body: 
   { status: 400,
     error: 'bad_request',
     reason: '"value"_length_must_be_20_characters_long' },
  headers: 
   { server: 'nginx/1.9.9',
     date: 'Fri, 07 Oct 2016 07:34:33 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '91',
     connection: 'keep-alive',
     'x-powered-by': 'Express',
     etag: 'W/"5b-37333810"',
     vary: 'Accept-Encoding' } } undefined { statusCode: 400,
  headers: 
   { server: 'nginx/1.9.9',
     date: 'Fri, 07 Oct 2016 07:34:33 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '91',
     connection: 'keep-alive',
     'x-powered-by': 'Express',
     etag: 'W/"5b-37203810"',
     vary: 'Accept-Encoding' },
  elapsedTime: 529 }


/home/user/hg2g/workspace/node_modules/classeur-downloader/bin/cldownload.js:11
        if (error) throw error;
                   ^

Error: Server error: Received HTTP code 400 for GET https://app.classeur.io/api/v1/folders/OpenStack
    at ErrorBase (/home/user/hg2g/workspace/node_modules/classeur-api-client/lib/errors.js:23:3)
    at ServerError (/home/user/hg2g/workspace/node_modules/classeur-api-client/lib/errors.js:110:3)
    at _client.get (/home/user/hg2g/workspace/node_modules/classeur-api-client/classeur-api-client.js:220:24)
    at /home/user/hg2g/workspace/node_modules/flashheart/lib/client.js:221:5
    at /home/user/hg2g/workspace/node_modules/flashheart/lib/client.js:203:5
    at onreponse (/home/user/hg2g/workspace/node_modules/levee/lib/breaker.js:120:18)
    at __container__ (/home/user/hg2g/workspace/node_modules/levee/lib/zalgo.js:17:26)
    at /home/user/hg2g/workspace/node_modules/flashheart/lib/client.js:194:7
    at Request._callback (/home/user/hg2g/workspace/node_modules/flashheart/lib/client.js:154:14)
    at Request.self.callback (/home/user/hg2g/workspace/node_modules/request/request.js:187:22)

```

**Comment by zbentley** [comment]
At present, you have to address everything in Classeur by ID (you can get the ID of an object from the URL bar, if you're using Classeur in your browser, or via the UID portion of the "share" link, if you're using the desktop application). See "Using IDs" in the [main documentation](http://zbentley.github.io/classeur-downloader/versions/latest/) for a bit more info.

This will hopefully change in a future release (when I add support for the v2 API).

**Comment by epcim** [comment]
Thanks with ID it continues, however as of now it downloads metadata, but content is empty. So it creates an empty file. Can be caused because I use your downloaded wrapper. Best if you may for future versions document/test full example usage against an public document.

**Comment by zbentley** [comment]
Digging into this today or tomorrow. Sorry for the long delay, and thanks for the report!

**Comment by zbentley** [comment]
This is because the `v1` API appears to have been unexpectedly broken, which is unfortunate. The "text" content that was previously included by Classeur is no longer present.

Either way, it's time to support `v2`. I'm closing this issue. The failure of `classeur-downloader` to work properly with file content can be tracked in zbentley/classeur-downloader#3

The real work will be done in zbentley/classeur-api-client#3, in which I'll add support that I can to the V2 API without changing this module's API.

Thanks for the bug report; please be patient. I will hopefully finish fixes/tests for the V2 API within the coming week.
